language: 'ko-KR'
reviews:
  auto_review:
    enabled: true              # 모든 PR을 자동 리뷰

  behavior:
    explain_code_complexity: true  # 코드의 복잡도를 같이 설명
    suggest_improvements: true     # 개선점을 적극적으로 제안
    ask_clarifying_questions: false

  comments:
    tone: "friendly"             # 친근하게
