repos:
  - repo: local
    hooks:
      - id: gradle-spotless
        name: Gradle Spotless Check
        entry: ./gradlew spotlessCheck
        language: system
        pass_filenames: false

      - id: gradle-check
        name: Gradle Build Check
        entry: ./gradlew check
        language: system
        pass_filenames: false

      - id: gradle-spotless-apply
        name: Spotless Auto Format
        entry: ./gradlew spotlessApply
        language: system
        pass_filenames: false

      - id: gradle-build-check
        name: Gradle Dry Run
        entry: ./gradlew build --dry-run
        language: system
        pass_filenames: false

      - id: gradle-test
        name: Gradle Test Run
        entry: ./gradlew test
        language: system
        pass_filenames: false
