name: Code Quality Check

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  java-check:
    name: Java Format & Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Run Gradle Checks
        run: ./gradlew check

      - name: Run Gradle Build
        run: ./gradlew build --dry-run

      - name: Run Gradle Test
        run: ./gradlew test

      - name: Run Spotless Format Check
        run: ./gradlew spotlessCheck

      - name: Run Spotless Auto Fix
        run: ./gradlew spotlessApply
